Feature/custom template
forviz/react-selectr pull request #21
Opened 2017-03-10 16:26 UTC by Doppy

Add feature 
 - Custom Option Renderer 
 - Custom Option Group Label Renderer

--- ยังไม่แน่ใจว่าจะใช้ชื่อ propTypes ว่าอะไรดี....ขอไอเดีย ---

2017-03-11 05:20 UTC, GA-MO requested changes

2017-03-11 05:20 UTC, GA-MO commented on src/Option.js
> +    const optionRenderer = this.props.customRenderOption || defaultRenderOption;
ลองเพิ่ม function optionRender() โดยจะส่ง UI จากการตัดสินใจแล้วว่าจะเป็น custom UI หรือ default UI

2017-03-11 05:20 UTC, GA-MO commented on src/Option.js
ลองเพิ่ม function optionRender() โดยจะส่ง UI จากการตัดสินใจแล้วว่าจะเป็น custom UI หรือ default UI

2017-03-11 05:20 UTC, GA-MO commented on src/Option.js
> +
รับเป็น value, label แบบเดิมน่าจะเข้าใจกว่า ในกรณี custom UI return 2 parameter เช่น customOptionUI(label, value)

2017-03-11 05:20 UTC, GA-MO commented on example/containers/App.js
> +            </div>
customRenderOption ส่ง 2 parameter น่าจะเข้าใจกว่า (label, value) จะได้ไม่ต้องเปลี่ยน props ใน option conponent ด้วย

2017-03-11 05:20 UTC, GA-MO commented on src/index.js
> +    customRenderOptionGroupLabel: PropTypes.func,
ลองพิจารณาชื่อพวกนี้ดูครับ
- customOptionUI
- customUIOption
- customOption

2017-03-12 06:34 UTC, Doppy commented on src/Option.js
อ่าา ยังไม่ค่อยเข้าใจเท่าไหร่??

2017-03-12 06:37 UTC, Doppy commented on src/Option.js
> +
ที่ทำแบบนี้เพราะว่าเผื่อกรณีจะ renderOption โดยใช้ parameter มากกว่า value, label ปกติน่ะ เช่นสมมติ

const options = [
  { value: 'sven', label: 'Sven', trait: 'Strength' },
  { value: 'drowranger', label: 'Drow Ranger', trait: 'agility' },
  { value: 'naix', label: 'Nyx', trait: 'inteligent' },
];

แล้วเราโยนทั้ง option ไปที่ renderOption (option) 

ใน render เราสามารถเพิ่มเงื่อนไขได้เช่น

render() {
  const option = this.props.option;
  switch (option.trait) {
    case 'Strength': return this.renderStrentghHeroOption(option);
    case 'Agility': return this.renderAgilityHeroOption(option);
  }
  

}

2017-03-12 06:37 UTC, Doppy commented on example/containers/App.js
> +            </div>
อ่าา ยังไม่ค่อยเข้าใจเท่าไหร่?? (เหมือนอันบน)

2017-03-12 06:37 UTC, Doppy commented on src/Option.js
> +    const optionRenderer = this.props.customRenderOption || defaultRenderOption;
อ่าา ยังไม่ค่อยเข้าใจเท่าไหร่??

2017-03-12 06:47 UTC, GA-MO commented on src/Option.js
> +
ผมว่า option ควรจะมีแค่ value, label อ่ะครับ parameter อื่นไม่น่าใช่ option
ในกรณีถ้ามีแล้ว renderOption() จะ render default เป็นแบบไหนครับ

2017-03-12 06:58 UTC, GA-MO commented on src/Option.js
> +    const optionRenderer = this.props.customRenderOption || defaultRenderOption;
ตอนนี้ defaultRenderOption เป็น static ที่ประกาศอยู่ด้านบนลองเพิ่ม
function optionRender(){
   const { label, value, customRenderOption  } = this.props;
   return customRenderOption(label, value) || (<span>{label}</span>);
}

2017-03-12 08:02 UTC, Doppy commented on src/Option.js
> +
สมมติถ้าอนุญาตให้ใส่ parameter อื่นที่ไม่ใช่ option ได้ด้วยเราจะสามารถทำอะไรแบบนี้ได้ด้วยนะ
คือ render แต่ละ option ให้หน้าตาไม่เหมือนกัน อิงจากค่าที่ส่งเข้ามา
![image](https://cloud.githubusercontent.com/assets/1094681/23830087/b323bffe-0734-11e7-9734-83093336d9ff.png)

ส่วน render default ก็จะมี value / label เป็น minimum

2017-03-12 08:10 UTC, Doppy commented on src/Option.js
> +    const optionRenderer = this.props.customRenderOption || defaultRenderOption;
ยังงงอยู่..... 
คืออยากให้จัดโค้ดให้เป็นระเบียบขึ้น โดยการรวบการ render option ให้เป็น function ของมัน? รึเปล่า?

2017-03-12 08:15 UTC, Doppy commented on example/containers/App.js
> +            </div>
คำตอบเหมือนกับ comment  อันบนนะ
ทำเป็น option กลางๆ ไว้เพื่อเผื่อคนใช้ค่าอื่นๆ ใน render object option
เช่น

{
  value: '5',
  label: 'Bangkok, Thailand - Suvarnabhumi International Airport',
  address: 'Racha theva, Thailand',
  type: 'airport',
},

2017-03-12 12:44 UTC, GA-MO commented on src/Option.js
> +    const optionRenderer = this.props.customRenderOption || defaultRenderOption;
อ่าประมาณนั้นครับ

2017-03-12 13:00 UTC, GA-MO commented on src/Option.js
> +
งั้นขอเสนอเพิ่ม disabled ไปใน option ด้วยครับแบบกดเลือกไม่ได้

2017-03-12 13:20 UTC, Doppy commented on src/Option.js
> +
👍

2017-03-16 15:15 UTC, Doppy commented on src/Option.js
แก้ละนะ

2017-03-16 15:16 UTC, Doppy commented on src/index.js
> +    customRenderOptionGroupLabel: PropTypes.func,
ขอยังใช้ชื่อเดิมละกันนะ คำว่า UI มันกินใจความกว้างไปหน่อย ยังรู้สึกว่าคำว่า render จะตรงความหมายกว่า

2017-03-20 02:37 UTC, GA-MO approved these changes

2017-03-20 05:25 UTC, merged